### ISSUE TITLE
bundle rake db error with mysql and redmine 3.3.3

### ISSUE THREAD

**Issue by archonwang** [TakiJoe/redmine_import_issues#2]
@TakiJoe , 
please help to check it. Thanks.

error log

```
[root@jira redmine-3.3]# bundle exec rake redmine:plugins:migrate NAME=redmine_import_issues  RAILS_ENV=production
Migrating redmine_import_issues (Import Issues plugin)...
== 1 CreateImportActions: migrating ===========================================
-- create_table(:import_actions)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

undefined method `longtext' for #<ActiveRecord::ConnectionAdapters::TableDefinition:0x0000000b73bfa8>
/opt/redmine-3.3/plugins/redmine_import_issues/db/migrate/001_create_import_actions.rb:17:in `block in change'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:216:in `create_table'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:474:in `create_table'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:665:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `say_with_time'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:654:in `method_missing'
/opt/redmine-3.3/plugins/redmine_import_issues/db/migrate/001_create_import_actions.rb:3:in `change'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:608:in `exec_migration'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:591:in `block in migrate'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:590:in `migrate'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:768:in `migrate'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1046:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:959:in `block in migrate'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `each'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `migrate'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:823:in `up'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:801:in `migrate'
/opt/redmine-3.3/lib/redmine/plugin.rb:481:in `migrate_plugin'
/opt/redmine-3.3/lib/redmine/plugin.rb:453:in `migrate'
/opt/redmine-3.3/lib/redmine/plugin.rb:464:in `migrate'
/opt/redmine-3.3/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
NoMethodError: undefined method `longtext' for #<ActiveRecord::ConnectionAdapters::TableDefinition:0x0000000b73bfa8>
/opt/redmine-3.3/plugins/redmine_import_issues/db/migrate/001_create_import_actions.rb:17:in `block in change'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:216:in `create_table'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:474:in `create_table'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:665:in `block in method_missing'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `say_with_time'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:654:in `method_missing'
/opt/redmine-3.3/plugins/redmine_import_issues/db/migrate/001_create_import_actions.rb:3:in `change'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:608:in `exec_migration'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:591:in `block in migrate'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:590:in `migrate'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:768:in `migrate'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1046:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:959:in `block in migrate'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `each'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `migrate'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:823:in `up'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:801:in `migrate'
/opt/redmine-3.3/lib/redmine/plugin.rb:481:in `migrate_plugin'
/opt/redmine-3.3/lib/redmine/plugin.rb:453:in `migrate'
/opt/redmine-3.3/lib/redmine/plugin.rb:464:in `migrate'
/opt/redmine-3.3/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)

```

**Comment by TakiJoe** [comment]
@archonwang I've already fixed this bug, you can try reinstall it again.

**Comment by archonwang** [comment]
@TakiJoe , Thanks, I will try it later.
