### ISSUE TITLE
no list showed in Data to import after select source to file redmine 3.3.1

### ISSUE THREAD

**Issue by excceed** [TakiJoe/redmine_import_issues#3]
When I'm using this import function and mapping source to a file, the Data to import don't show the drop list of coloum name in file.

> 
 Current user: admin (id=1)
Completed 500 Internal Server Error in 995ms (ActiveRecord: 22.0ms)

NoMethodError (undefined method `upcase' for 2:Fixnum):
  plugins/redmine_import_issues/app/controllers/importer_issues_controller.rb:146:in `block in load_values_for_field'
  plugins/redmine_import_issues/app/controllers/importer_issues_controller.rb:146:in `select'
  plugins/redmine_import_issues/app/controllers/importer_issues_controller.rb:146:in `load_values_for_field'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode
> 

--------------------------------------------------------------------------------
Environment:
  Redmine version                3.3.3.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [i386-mingw32]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  quick_view                     0.3.0
  redmine_base_deface            0.0.1
  redmine_checklists             3.1.6
  redmine_issue_dynamic_edit     0.4.2
  redmine_issue_templates        0.1.8
  redmine_multiprojects_issue    3.3.0
  redmine_plugin_views_revisions 0.0.1
  redmine_user_import            0.1.0
  redmine_xls_export             0.2.1.t10
  sidebar_hide                   0.0.8

**Comment by excceed** [comment]
someone help me？

**Comment by excceed** [comment]
Sorry, this problem is a fake one. :)
It occurs only if you use the template file which has 2 same column name.
